FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ../src ./src
COPY ../Ecommerce.sln ./
RUN dotnet restore "src/WebApi/WebApi.csproj" \
    && dotnet publish "src/WebApi/WebApi.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "WebApi.dll"]