ARG NEXT_APP
FROM node:20 AS build
WORKDIR /usr/src/app
COPY ../../package*.json ./
COPY ../../apps/${NEXT_APP}/package*.json ./apps/${NEXT_APP}/
RUN npm install
COPY ../../apps/${NEXT_APP} ./
ENV NODE_ENV=production
RUN npm run build

FROM node:20 AS runtime
WORKDIR /usr/src/app
ENV NODE_ENV=production
COPY --from=build /usr/src/app/.next ./.next
COPY --from=build /usr/src/app/package*.json ./
COPY --from=build /usr/src/app/public ./public
EXPOSE 3000
CMD ["npm", "start"]